version: "3.9"

services:
  web:
    build: .
    container_name: django_server
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres_database
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
  news_collector:
    build: .
    container_name: news_collector
    command: python manage.py crawl
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - db