version: "3.9"

services:
  web:
    build: .
    container_name: django_server
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  makemigration:
    build: .
    container_name: django_migrations
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --no-input --clear"
    volumes:
      - .:/code
    depends_on:
      - web
      - db
  db:
    image: postgres
    container_name: postgres_database_2
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
  celery:
    build:
      context: .
    command: celery -A MyAssistantProject worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
      - rabbit_mq

  rabbit_mq:
    container_name: "RabbitMQ_Server"
    image: rabbitmq:3.10-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"


